name: Deploy generated output
on:
  push:
    branches:
      - main

jobs:
 publish:
  name: generate HTML
  runs-on: ubuntu-latest
  steps:
  - uses: actions/checkout@v2
  - uses: baileyjm02/markdown-to-pdf@v1
    with:
      input_dir: .
      output_dir: output
      build_html: true
      # images_dir: docs/images
      # image_import: ./images
  - uses: actions/upload-artifact@v1
    with:
      name: upload
      path: output
